#define BOARD BOARD_CUSTOM

#define IMU IMU_ICM45686
#define IMU_ROTATION DEG_0

#define MAX_IMU_COUNT 4

#define SENSOR_DESC_LIST \
    SENSOR_DESC_ENTRY(IMU, 0x69, DEG_0, DIRECT_WIRE(5, 4), true) \
    SENSOR_DESC_ENTRY(IMU, 0x68, DEG_0, DIRECT_WIRE(5, 4), true) \
    SENSOR_DESC_ENTRY(IMU, 0x69, DEG_0, DIRECT_WIRE(1, 0), true) \
    SENSOR_DESC_ENTRY(IMU, 0x68, DEG_0, DIRECT_WIRE(1, 0), true) \

// #define PIN_IMU_SDA 4
// #define PIN_IMU_SCL 5
// #define PIN_IMU_INT 6
// #define PIN_IMU_INT_2 7
// #define PIN_IMU_INT_3 10
// #define PIN_BATTERY_LEVEL 3

#define BATTERY_MONITOR BAT_EXTERNAL
#define BATTERY_SHIELD_RESISTANCE 0
#define BATTERY_SHIELD_R1 10
#define BATTERY_SHIELD_R2 40.2
